### ISSUE TITLE
Kindle 是否有无线同步或者在线下载笔记的功能？

### ISSUE THREAD

**Issue by GeneralLi95** [muzi502/kindle#1]
这个功能非常棒。一点疑问，每次需要手动从Kindle拷出笔记么？这可能是一个痛点。

**Comment by muzi502** [comment]
写个 .bat 脚本就行，kindle 解锁屏幕后，插上 USB 数据线，然后再手动执行这个脚本即可

把 src 路径的盘符修改为你 PC 上 kindle 的盘符，dist 路径修改为这个项目的 source.txt 的路径即可。
另外也可以把 kindle 截屏图片复制出来，根据自己的环境修改相应的路径即可。

```
set src="G:\documents\My Clippings.txt"
set dist=D:\Desktop\kindlenote\source.txt
set pngsrc=G:\*.png
set pngdist=F:\OneDrive\Kindle\Kindle
copy /Y  %src% %dist%
move /Y %pngsrc% %pngdist%
del /f G:\*.txt
```

**Comment by GeneralLi95** [comment]
感觉还是稍显复杂，先不折腾这个了。谢谢，又抄了你的 friend 方法，第一个把你的博客放了进去。
